// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mkBoutiqueCaftan.Data;

#nullable disable

namespace mkBoutiqueCaftan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129225219_AddPhotoCINToReservations")]
    partial class AddPhotoCINToReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdArticle"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Couleur")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("couleur");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int")
                        .HasColumnName("id_categorie");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<int?>("IdTaille")
                        .HasColumnType("int")
                        .HasColumnName("id_taille");

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom_article");

                    b.Property<string>("Photo")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("photo");

                    b.Property<decimal>("PrixAvanceBase")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("prix_avance_base");

                    b.Property<decimal>("PrixLocationBase")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("prix_location_base");

                    b.HasKey("IdArticle");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Articles_id_societe");

                    b.HasIndex("IdTaille");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categorie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategorie"));

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom_categorie");

                    b.Property<int?>("OrdreAffichage")
                        .HasColumnType("int")
                        .HasColumnName("ordre_affichage");

                    b.HasKey("IdCategorie");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Categories_id_societe");

                    b.HasIndex("NomCategorie", "IdSociete")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_NomCategorie_Societe");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("AdressePrincipale")
                        .HasColumnType("TEXT")
                        .HasColumnName("adresse_principale");

                    b.Property<DateTime>("DateCreationFiche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation_fiche")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_client");

                    b.Property<string>("PrenomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prenom_client");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.Property<int>("TotalCommandes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_commandes");

                    b.HasKey("IdClient");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Clients_id_societe");

                    b.HasIndex("Telephone", "IdSociete")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_Telephone_Societe");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_paiement");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_paiement")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int")
                        .HasColumnName("id_reservation");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<string>("MethodePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("methode_paiement");

                    b.Property<decimal>("Montant")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("montant");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference");

                    b.HasKey("IdPaiement");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Paiements_id_societe");

                    b.ToTable("Paiements", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reservation");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReservation"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("DATE")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("DATE")
                        .HasColumnName("date_fin");

                    b.Property<DateTime>("DateReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_reservation")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<int?>("IdPaiement")
                        .HasColumnType("int")
                        .HasColumnName("id_paiement");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("montant_total");

                    b.Property<string>("PhotoCIN")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("photo_cin");

                    b.Property<decimal>("RemiseAppliquee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("remise_appliquee");

                    b.Property<int>("StatutReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("statut_reservation");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdPaiement")
                        .IsUnique();

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Reservations_id_societe");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.ReservationArticle", b =>
                {
                    b.Property<int>("IdReservation")
                        .HasColumnType("int")
                        .HasColumnName("id_reservation");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int")
                        .HasColumnName("id_article");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantite");

                    b.HasKey("IdReservation", "IdArticle");

                    b.HasIndex("IdArticle");

                    b.ToTable("ReservationArticles", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom_role");

                    b.HasKey("IdRole");

                    b.HasIndex("NomRole")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_NomRole");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Societe", b =>
                {
                    b.Property<int>("IdSociete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSociete"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_societe");

                    b.Property<string>("SiteWeb")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("site_web");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdSociete");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Societes_Email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("NomSociete")
                        .IsUnique()
                        .HasDatabaseName("IX_Societes_NomSociete");

                    b.ToTable("Societes", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Taille", b =>
                {
                    b.Property<int>("IdTaille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_taille");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTaille"));

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("taille");

                    b.HasKey("IdTaille");

                    b.HasIndex("IdSociete")
                        .HasDatabaseName("IX_Tailles_id_societe");

                    b.HasIndex("Libelle", "IdSociete")
                        .IsUnique()
                        .HasDatabaseName("IX_Tailles_Libelle_Societe");

                    b.ToTable("Tailles", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.User", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<DateTime>("DateCreationCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation_compte")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    b.Property<int>("IdSociete")
                        .HasColumnType("int")
                        .HasColumnName("id_societe");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mot_de_passe_hash");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom_complet");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdSociete");

                    b.HasIndex("Email", "IdSociete")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Societe");

                    b.HasIndex("Login", "IdSociete")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Login_Societe");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Article", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mkBoutiqueCaftan.Models.Taille", "Taille")
                        .WithMany()
                        .HasForeignKey("IdTaille")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");

                    b.Navigation("Societe");

                    b.Navigation("Taille");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Categorie", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Client", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Paiement", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Reservation", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("mkBoutiqueCaftan.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mkBoutiqueCaftan.Models.Paiement", "Paiement")
                        .WithOne("Reservation")
                        .HasForeignKey("mkBoutiqueCaftan.Models.Reservation", "IdPaiement")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Client");

                    b.Navigation("Paiement");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.ReservationArticle", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mkBoutiqueCaftan.Models.Reservation", "Reservation")
                        .WithMany("ReservationArticles")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Taille", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.User", b =>
                {
                    b.HasOne("mkBoutiqueCaftan.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mkBoutiqueCaftan.Models.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("IdSociete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Paiement", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Reservation", b =>
                {
                    b.Navigation("ReservationArticles");
                });

            modelBuilder.Entity("mkBoutiqueCaftan.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
